id: 88d8eb81f454429ea6225c6595f6ec32
initial_creation_type: ocr
source_metadata:
  volumes:
    347114880d49434581337454fa41a162:
      base_file: v024.txt
      image_group_id: I1PD95869
      title: རལ་གྲི་གཤིན་རྗེ་གཤེད་གཏུམ་པོའི་སྒྲུབ་ཐབས།
      total_pages: 1586
      volume_number: 24
